#!/usr/bin/env node
// Generates src/seeds/seed.sql
// Run: node scripts/generate_seed.js

const fs = require('fs')
const path = require('path')

const lines = []
const w = (s) => lines.push(s)

w('-- Zudio seed data — generated by scripts/generate_seed.js')
w('-- Run AFTER migration: psql -d zudio_db -f src/seeds/seed.sql')
w('')

// ── CATEGORIES ────────────────────────────────────────────────
w('-- Categories')
w("INSERT INTO categories (name, description) VALUES")
w("  ('Shirts',      'Casual and formal shirts for men, women and kids'),")
w("  ('Trousers',    'Jeans, chinos, palazzos and formal trousers'),")
w("  ('Dresses',     'Kurtis, anarkalis, midi and maxi dresses'),")
w("  ('Footwear',    'Casual sneakers, formal shoes, heels and sandals'),")
w("  ('Accessories', 'Bags, belts, wallets, caps and sunglasses');")
w('')

// ── PRODUCTS (200) ────────────────────────────────────────────
const shirts = [
  ["Men's Classic Oxford Shirt","Full-sleeve cotton Oxford shirt, perfect for office",999],
  ["Men's Linen Blend Shirt","Breathable linen-cotton shirt for summer days",899],
  ["Men's Mandarin Collar Shirt","Minimalist mandarin collar shirt in solid colours",799],
  ["Men's Checked Flannel Shirt","Soft flannel check shirt for casual weekends",699],
  ["Men's Slim Fit Formal Shirt","Stretch-cotton slim fit shirt for a sharp look",1199],
  ["Men's Half-Sleeve Polo","Pique cotton polo with contrast collar trim",499],
  ["Men's Printed Casual Shirt","Tropical leaf print rayon shirt for outings",599],
  ["Men's Denim Shirt","Classic blue denim shirt with snap buttons",849],
  ["Men's Kurta Shirt","Short straight-cut kurta shirt with pintuck detailing",749],
  ["Men's Nehru Jacket Shirt","Festive Nehru collar shirt with mirror embroidery",1099],
  ["Women's Chiffon Ruffle Shirt","Flowy chiffon blouse with ruffle front panel",699],
  ["Women's Crop Tie-Front Shirt","Cropped cotton shirt with front tie knot",499],
  ["Women's Printed Georgette Top","Light georgette top with abstract block print",549],
  ["Women's Puff Sleeve Blouse","Trendy puff-sleeve cotton blouse",599],
  ["Women's Striped Linen Top","Relaxed-fit linen blend striped top",649],
  ["Women's Embroidered Kurti Shirt","Cotton kurti with thread embroidery at neckline",799],
  ["Women's Off-Shoulder Top","Bardot off-shoulder top in solid jersey",449],
  ["Women's Oversized Graphic Tee","Oversized tee with abstract graphic print",399],
  ["Kids' Superhero Tee","100% cotton tee with superhero print, sizes 2-12",299],
  ["Kids' Polo Set","Cotton polo shirt and shorts co-ord set",499],
  ["Men's V-Neck Cotton Tee","Everyday V-neck tee in 12 colour options",349],
  ["Men's Henley Tee","Buttoned henley collar casual tee",379],
  ["Men's Raglan Tee","Colour-block raglan sleeve tee",329],
  ["Women's Sleeveless Kurta","Summer sleeveless straight-cut kurta",649],
  ["Women's Cold-Shoulder Top","Cut-out cold-shoulder jersey top",429],
  ["Men's Slim Fit Half-Sleeve Formal","Formal half sleeve shirt with micro-check pattern",949],
  ["Women's Tie-Dye T-Shirt","Hand tie-dye effect oversized tee",449],
  ["Kids' Dinosaur Print Tee","Bright dinosaur graphic tee for toddlers",279],
  ["Men's Resort Print Shirt","Relaxed camp-collar resort print shirt",699],
  ["Women's Button-Down Chambray","Classic chambray button-down with rolled sleeves",749],
  ["Men's Mock-Neck Full Sleeve","Ribbed mock-neck full-sleeve tee",599],
  ["Women's Asymmetric Hem Top","Cotton top with asymmetric curved hem",479],
  ["Men's Festival Kurta","Bandhani print cotton kurta for festive season",849],
  ["Women's Smocked Peasant Top","Elasticated smocked neckline peasant top",549],
  ["Kids' Unicorn Print Tee","Glitter unicorn graphic tee for girls",319],
  ["Men's Burnout Tee","Distressed burnout wash crew-neck tee",429],
  ["Women's Lace Insert Top","Woven top with lace insert at yoke",629],
  ["Men's Corduroy Shirt","Soft cord shirt in warm autumn shades",899],
  ["Women's Wrap Blouse","Satin-look wrap blouse with long ties",699],
  ["Men's Waffle Knit Tee","Textured waffle knit short-sleeve tee",449],
]

const trousers = [
  ["Men's Slim Fit Chinos","Cotton chinos in slim taper fit, 8 colours",999],
  ["Men's Straight Leg Jeans","Classic straight fit mid-rise blue jeans",1199],
  ["Men's Skinny Jeans","Stretch denim skinny jeans for a sharp silhouette",1099],
  ["Men's Formal Flat-Front Trousers","Polycotton slim flat-front office trousers",1299],
  ["Men's Cargo Pants","Multi-pocket cotton cargo in olive and khaki",1199],
  ["Men's Jogger Track Pants","Fleece-lined jogger with contrast zip pockets",799],
  ["Men's Ankle-Length Trousers","Cropped ankle-length trousers for smart casual",899],
  ["Men's Distressed Jeans","Ripped knee distressed slim jeans",1249],
  ["Women's High-Waist Straight Jeans","High-rise straight-leg jeans in indigo blue",1299],
  ["Women's Relaxed Wide-Leg Jeans","Relaxed wide-leg jeans with frayed hem",1399],
  ["Women's Palazzo Pants","Flowy printed palazzo pants in georgette",699],
  ["Women's Cigarette Trousers","Tailored cigarette trousers in check fabric",1099],
  ["Women's Jeggings","Super-stretch jeggings in 6 washes",899],
  ["Women's Cotton Salwar","Straight-cut printed cotton salwar",549],
  ["Women's Flare Jeans","Bell-bottom flare jeans with 70s vibe",1199],
  ["Kids' Elastic Waist Joggers","Soft cotton jogger with elasticated waistband",449],
  ["Kids' Denim Pull-On Jeans","Comfortable pull-on denim jeans for toddlers",499],
  ["Men's Linen Trousers","Lightweight linen trousers for warm weather",1099],
  ["Men's Drawstring Shorts","Cotton drawstring shorts above the knee",499],
  ["Women's Paperbag Trousers","Belted paperbag-waist trousers in blush",1149],
  ["Men's Tapered Joggers","Slim tapered jogger in tech-stretch fabric",899],
  ["Women's Printed Harem Pants","Boho printed harem pants in rayon",649],
  ["Men's Corduroy Pants","Wide-rib corduroy trousers in tan",1199],
  ["Women's Fitted Jeggings","Ultra-stretch fitted jeggings with faux front pockets",799],
  ["Men's Bermuda Shorts","Smart chino-style bermuda shorts",699],
  ["Women's Culottes","Knee-length culottes in crepe fabric",749],
  ["Men's Pyjama Bottoms","Soft woven pyjama bottoms with side seam pockets",399],
  ["Women's Track Pants","Relaxed track pants with stripe detail",649],
  ["Men's Linen-Blend Shorts","Casual linen blend shorts with drawstring",549],
  ["Women's Crop Wide-Leg Pants","Cropped wide-leg pants in satin finish",999],
  ["Men's Five-Pocket Twill Pants","Durable twill five-pocket pants in stone",1099],
  ["Women's Knit Leggings","Thick knit thermal leggings for winter",599],
  ["Men's Slim Suit Trousers","Part of the Zudio formal suit range",1499],
  ["Women's Pintuck Trousers","Elegant front pintuck wide trousers",1099],
  ["Men's Printed Pyjama Set","100% cotton printed pyjama set (top + bottom)",799],
  ["Kids' Cargo Shorts","Multi-pocket cargo shorts for active kids",449],
  ["Women's Cigarette Pants Linen","Linen cigarette pants with side zip",1149],
  ["Men's Relaxed Fit Jeans","Comfortable relaxed-fit mid-blue jeans",1199],
  ["Women's Denim Shorts","High-waist frayed denim cut-off shorts",799],
  ["Men's Active Dry-Fit Shorts","Quick-dry active shorts with inner liner",499],
]

const dresses = [
  ["Women's Floral Wrap Dress","Floral print wrap dress in chiffon with v-neckline",1299],
  ["Women's A-Line Midi Dress","Flared A-line midi dress in cotton poplin",1099],
  ["Women's Bodycon Dress","Stretch bodycon dress for evening occasions",899],
  ["Women's Anarkali Kurti","Floor-length anarkali kurti with mirror work",1499],
  ["Women's Shift Dress","Clean-line sleeveless shift dress in solid colour",799],
  ["Women's Shirt Dress","Belted shirt dress in chambray denim",1199],
  ["Women's Maxi Boho Dress","Tiered boho maxi dress with tassel trim",1399],
  ["Women's Smock Dress","Elasticated smock dress with puff sleeves",999],
  ["Women's Kaftan Dress","Printed kaftan tunic dress for resort wear",1199],
  ["Women's Skater Dress","Fit-and-flare skater dress with zip back",899],
  ["Women's Printed Saree-Style Dress","Pre-stitched saree-look dress in satin",1999],
  ["Women's Peplum Dress","Peplum hem bodycon dress for parties",1099],
  ["Women's Off-Shoulder Midi","Off-shoulder tiered midi dress in floral print",1299],
  ["Women's Straight Kurti","Cotton straight kurti with block print yoke",749],
  ["Women's Empire-Waist Maxi","Gathered empire-waist maxi dress in georgette",1499],
  ["Women's Denim Pinafore Dress","Adjustable strap denim pinafore over tee",1099],
  ["Women's Pleated Party Dress","Satiny pleated mini dress for celebrations",999],
  ["Women's Linen Shirt Dress","Relaxed linen shirt dress with patch pockets",1199],
  ["Women's Halter Neck Dress","Halter neck dress with open tie back",899],
  ["Women's Ombre Dress","Gradient ombre dip-dye midi dress",1099],
  ["Women's Collar Neck Dress","Preppy collared mini dress in gingham",849],
  ["Girls' Party Frock","Tulle layered party frock with satin bow",699],
  ["Girls' Floral Sundress","Liberty-print cotton sundress with smocking",549],
  ["Women's Cold Shoulder Dress","Cut-out cold-shoulder dress in solid jersey",799],
  ["Women's Printed Chiffon Dress","Flowy chiffon printed midi with elastic waist",999],
  ["Women's Dungaree Dress","Denim dungaree dress with adjustable straps",1199],
  ["Women's Cutout Dress","Asymmetric side-cutout bodycon dress",999],
  ["Women's Sequin Mini Dress","Sequin embellished mini dress for nights out",1999],
  ["Women's Folk Embroidery Dress","Phulkari-inspired embroidered cotton dress",1599],
  ["Women's Ruched Side Dress","Ruched side detail bodycon midi dress",899],
  ["Women's Square-Neck Sun Dress","Strappy square-neck cotton sundress",749],
  ["Women's Midi Shirt Dress","Belted midi shirt dress with rolled sleeves",1099],
  ["Women's Velvet Wrap Dress","Rich velvet wrap dress for winter evenings",1799],
  ["Women's Broderie Anglaise Dress","White broderie anglaise midi dress",1299],
  ["Women's Boho Crop Dress","Bohemian tie-dye crop-top skirt set",899],
  ["Girls' Co-Ord Set","Top and skirt two-piece co-ord set for girls",599],
  ["Women's Abstract Print Dress","Abstract watercolour print chiffon dress",1099],
  ["Women's Balloon Sleeve Dress","Puffed balloon-sleeve midi in pastel",999],
  ["Women's Tube Mini Dress","Stretch tube bandeau mini dress",749],
  ["Women's Resort Kaftan","Lightweight resort kaftan with drawstring hem",1399],
]

const footwear = [
  ["Men's Canvas Sneakers","Lightweight cotton canvas sneakers in 8 colours",999],
  ["Men's Leather Derby Shoes","Smooth leather Derby shoes with cushioned sole",2499],
  ["Men's Sports Running Shoes","Mesh upper running shoes with EVA midsole",1999],
  ["Men's Loafers","Slip-on moccasin loafers in tan leather",1799],
  ["Men's Kolhapuri Sandals","Traditional Maharashtrian Kolhapuri chappals",899],
  ["Men's Mojari","Embroidered ethnic mojari shoes for festive wear",1299],
  ["Men's Flip Flops","Thick-sole rubber flip flops for beach and home",399],
  ["Men's Chelsea Boots","Elastic side-panel Chelsea boots in suede-look",2999],
  ["Men's Sports Sandals","Adjustable strap velcro sports sandals",799],
  ["Men's Formal Oxford","Lace-up Oxford with brogue detailing",2299],
  ["Women's Block Heel Sandals","Chunky block heel ankle-strap sandals",1499],
  ["Women's Pointed Stilettos","Slim stiletto heels for formal occasions",1999],
  ["Women's Ballet Flats","Classic round-toe ballet flats with bow",899],
  ["Women's Platform Sneakers","Platform sole chunky sneakers",1599],
  ["Women's Wedge Sandals","Espadrille wedge sandals in jute",1299],
  ["Women's Strappy Kitten Heels","Thin-strap kitten heel sandals in gold",1499],
  ["Women's Slip-On Mules","Backless slip-on mule heels",1199],
  ["Women's Sport Slides","Cushioned foam sport slide sandals",599],
  ["Women's Ethnic Jutti","Embroidered punjabi jutti with pom-pom trim",1099],
  ["Women's Peep-Toe Heels","Slingback peep-toe heels in patent finish",1799],
  ["Kids' School Shoes","Black leather-look velcro school shoes",799],
  ["Kids' Canvas Sneakers","Colourful canvas trainers with velcro closure",699],
  ["Kids' Sandals","Adjustable strap rubber sandals in bright colours",499],
  ["Kids' Rain Boots","Waterproof rubber rain boots with cartoon print",799],
  ["Men's Boat Shoes","Canvas deck/boat shoes in navy and white",1199],
  ["Women's Clog Sandals","Wooden-sole clog sandals in leather upper",1399],
  ["Men's Trekking Shoes","Rugged ankle trekking shoes with grip sole",2499],
  ["Women's Jelly Sandals","PVC translucent jelly sandals",549],
  ["Men's Casual Moccasins","Soft suede-look casual moccasin slip-ons",999],
  ["Women's Thong Sandals","Minimalist toe-post flat sandals",699],
  ["Men's Mesh Sneakers","Breathable knit-mesh casual sneakers",1299],
  ["Women's Ankle Boots","Zip-up ankle boots with block heel",1999],
  ["Kids' Light-Up Sneakers","LED light-up sole sneakers for kids",999],
  ["Men's Velcro Sandals","Dual-strap velcro walking sandals",799],
  ["Women's Knee-High Boots","Faux suede tall knee-high boots",2999],
  ["Men's Woven Leather Sandals","Italian-style woven leather sandals",1299],
  ["Women's Sneaker Wedges","Hidden-wedge sole sneakers",1499],
  ["Men's Driving Shoes","Soft pebbled leather driving moccasins",1899],
  ["Women's Platform Mules","Chunky platform heel backless mules",1599],
  ["Kids' Flip Flops","Soft foam flip flops in neon colours",299],
]

const accessories = [
  ["Canvas Tote Bag","Large cotton canvas tote with interior zip pocket",599],
  ["Leather Crossbody Bag","Compact faux-leather crossbody bag with chain strap",1299],
  ["Backpack","Lightweight poly backpack with laptop sleeve",1799],
  ["Clutch Purse","Embellished sequin clutch for evening events",899],
  ["Bum Bag","Canvas bum bag / fanny pack with multi pockets",699],
  ["Fabric Belt","Braided cotton fabric belt in tan and navy",299],
  ["Leather Belt","Smooth genuine leather belt with brushed buckle",799],
  ["Reversible Belt","Reversible leather belt — black one side, brown other",999],
  ["Bi-Fold Leather Wallet","Slim genuine leather wallet with 8 card slots",799],
  ["Long Wallet","Zip-around long wallet with coin pouch",999],
  ["Card Holder","Slim aluminium RFID-block card holder",499],
  ["Sunglasses - Wayfarers","Classic wayfarer sunglasses with UV400 lenses",699],
  ["Sunglasses - Aviators","Metal frame aviator sunglasses in silver/gold",799],
  ["Baseball Cap","Cotton twill logo baseball cap in 6 colours",399],
  ["Bucket Hat","Wide-brim canvas bucket hat for sun protection",449],
  ["Beanie","Ribbed knit beanie in warm shades for winter",349],
  ["Stole / Scarf","Lightweight cotton printed stole",399],
  ["Pashmina Shawl","Soft wool-blend pashmina shawl",999],
  ["Wristwatch - Classic","Minimalist quartz wristwatch with leather strap",2499],
  ["Wristwatch - Sport","Digital sports watch with backlight and timer",1499],
  ["Stud Earrings Set","Pack of 6 pairs assorted metal stud earrings",349],
  ["Hoop Earrings","Gold-tone oversized hoop earrings",499],
  ["Statement Necklace","Beaded statement necklace for ethnic wear",699],
  ["Layered Necklace Set","Dainty layered gold-tone necklace set",599],
  ["Bangle Set","Set of 12 assorted bangles in mixed finishes",399],
  ["Charm Bracelet","Silver-tone charm bracelet with fashion pendants",449],
  ["Men's Bracelet Set","Set of 3 leather and metal bracelets",399],
  ["Scrunchie Set","Pack of 10 satin scrunchies in assorted colours",199],
  ["Hair Clip Set","Pack of 8 acrylic claw clips — mix of sizes",299],
  ["Travel Pouch Set","Set of 3 canvas pouches in various sizes",549],
  ["Luggage Tag","Personalised PU leather luggage tag",299],
  ["Phone Wallet Case","Stick-on card holder for phone back",249],
  ["Umbrella - Compact","Wind-resistant foldable compact umbrella",799],
  ["Umbrella - Full Size","Auto-open-close full-size branded umbrella",999],
  ["Belt Bag","Slim belt bag in nylon with zip closure",749],
  ["Duffle Bag","Weekend duffle bag in poly canvas",1999],
  ["Laptop Bag","Padded laptop bag fits up to 15.6 inch",1799],
  ["Jewellery Box","Velvet-lined travel jewellery organiser box",699],
  ["Key Holder","Leather multi-hook key holder pouch",349],
  ["Tie & Pocket Square Set","Woven silk-look tie with matching pocket square",799],
]

// all 200 products: [name, description, price, categoryOffset (1-5)]
const allProducts = [
  ...shirts.map(p => [...p, 1]),
  ...trousers.map(p => [...p, 2]),
  ...dresses.map(p => [...p, 3]),
  ...footwear.map(p => [...p, 4]),
  ...accessories.map(p => [...p, 5]),
]

// image placeholder URLs by category
const imgBases = {
  1: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400',
  2: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
  3: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400',
  4: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
  5: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
}

w('-- Products (200)')
w('INSERT INTO products (name, description, price, stock, category_id, image_url) VALUES')
const prodRows = allProducts.map(([name, desc, price, cat], i) => {
  const stock = 50 + Math.floor(((price * 7 + i * 13) % 200))
  const img = imgBases[cat]
  const safe = (s) => s.replace(/'/g, "''")
  return `  ('${safe(name)}', '${safe(desc)}', ${price}.00, ${stock}, ${cat}, '${img}')`
})
w(prodRows.join(',\n') + ';')
w('')

// ── USERS (50) ────────────────────────────────────────────────
const userNames = [
  'Aarav Sharma','Priya Patel','Rohan Mehta','Sneha Gupta','Vikram Nair',
  'Ananya Iyer','Karan Joshi','Pooja Singh','Arjun Reddy','Divya Pillai',
  'Rahul Verma','Kavya Krishnan','Aditya Kumar','Deepika Bose','Nikhil Malhotra',
  'Shreya Desai','Amit Chauhan','Ishaan Kapoor','Riya Chatterjee','Siddharth Rao',
  'Meera Nambiar','Farhan Qureshi','Tanvi Shah','Harsh Srivastava','Nidhi Agarwal',
  'Vivek Pandey','Swathi Menon','Akash Yadav','Simran Kaur','Gaurav Tiwari',
  'Pallavi Dubey','Tarun Banerjee','Madhuri Naidu','Lokesh Mishra','Asha Venkatesh',
  'Chirag Bhatt','Jyoti Saxena','Pankaj Rastogi','Kritika Singhania','Bhavesh Naik',
  'Sakshi Tripathi','Yash Kothari','Naina Bhatia','Alok Garg','Radhika Suresh',
  'Manish Lal','Chandani Parekh','Suraj Patil','Leena Hegde','Devika Mohan',
]

const toEmail = (name) => name.toLowerCase().replace(/\s+/g,'.')+'@example.com'

w('-- Users (50 — passwords stored plaintext, intentional bug)')
w('INSERT INTO users (name, email, password, phone, role) VALUES')
const userRows = userNames.map((name, i) => {
  const email = toEmail(name)
  const pw = name.split(' ')[0].toLowerCase() + (1000 + i)
  const phone = `9${String(800000000 + i * 7919).slice(0, 9)}`
  const role = i === 48 ? 'admin' : 'customer'
  return `  ('${name}', '${email}', '${pw}', '${phone}', '${role}')`
})
w(userRows.join(',\n') + ';')
w('')

// ── COUPONS (20) ──────────────────────────────────────────────
const couponData = [
  ['ZUDIO100',100,false,30],['WELCOME50',50,false,60],['SUMMER200',200,false,15],
  ['FEST150',150,false,7],['FLAT500',500,false,3],['NEWUSER75',75,false,45],
  ['SALE300',300,false,10],['VIP1000',1000,false,20],['FLASH250',250,false,2],
  ['BIRTHDAY200',200,false,365],['USED10',10,true,30],['EXPIRED50',50,false,-5],
  ['USED200',200,true,30],['CLEARANCE400',400,false,5],['MONSOON150',150,false,25],
  ['ENDSEASON300',300,false,8],['USED500',500,true,30],['DIWALI750',750,false,14],
  ['USED100',100,true,30],['WINTER500',500,false,60],
]

w('-- Coupons (20)')
w('INSERT INTO coupons (code, discount_amount, used, expires_at) VALUES')
const couponRows = couponData.map(([code,amt,used,days]) =>
  `  ('${code}', ${amt}.00, ${used}, NOW() + INTERVAL '${days} days')`
)
w(couponRows.join(',\n') + ';')
w('')

// ── ORDERS + ORDER_ITEMS ───────────────────────────────────────
// Each of 50 users gets 5-15 orders, each order 2-8 items
// Total order_items ~ 50 * 10 * 5 = 2500 rows

w('-- Orders and order_items')
w('-- Using a DO block so we can loop and generate realistic volumes')
w('DO $$')
w('DECLARE')
w('  uid       INT;')
w('  ord_id    INT;')
w('  num_orders INT;')
w('  num_items  INT;')
w('  prod_id    INT;')
w('  qty        INT;')
w('  uprice     NUMERIC(10,2);')
w('  pname      VARCHAR;')
w('  total      NUMERIC(10,2);')
w('  statuses   TEXT[] := ARRAY[\'pending\',\'confirmed\',\'shipped\',\'delivered\',\'delivered\',\'delivered\'];')
w('  addresses  TEXT[] := ARRAY[')
w("    '12 Brigade Road, Bengaluru 560001',")
w("    '45 Park Street, Kolkata 700016',")
w("    '7 Linking Road, Mumbai 400050',")
w("    '88 Connaught Place, New Delhi 110001',")
w("    '23 Anna Salai, Chennai 600002',")
w("    '56 MG Road, Pune 411001',")
w("    '9 Jubilee Hills, Hyderabad 500033',")
w("    '3 CG Road, Ahmedabad 380009',")
w("    '77 Residency Road, Bengaluru 560025',")
w("    '14 Salt Lake, Kolkata 700064'")
w('  ];')
w('  seed      INT := 0;')
w('BEGIN')
w('  FOR uid IN 1..50 LOOP')
w('    num_orders := 5 + (uid * 3 + 7) % 11;  -- 5 to 15')
w('    FOR o IN 1..num_orders LOOP')
w('      seed := seed + 1;')
w('      INSERT INTO orders (user_id, total_amount, discount, shipping_address, status, created_at)')
w('      VALUES (')
w('        uid,')
w('        0,')
w('        0,')
w('        addresses[(seed % 10) + 1],')
w("        statuses[(seed % 6) + 1],")
w("        NOW() - ((seed % 365) || ' days')::INTERVAL")
w('      ) RETURNING id INTO ord_id;')
w('')
w('      total := 0;')
w('      num_items := 2 + (seed * 17 + uid) % 7;  -- 2 to 8')
w('      FOR i IN 1..num_items LOOP')
w('        seed := seed + 1;')
w('        prod_id := (seed * 31 + uid * 7 + i * 13) % 200 + 1;')
w('        qty     := 1 + (seed + i) % 3;')
w('')
w('        SELECT price, name INTO uprice, pname FROM products WHERE id = prod_id;')
w('')
w('        INSERT INTO order_items (order_id, product_id, product_name, product_price, quantity, unit_price)')
w('        VALUES (ord_id, prod_id, pname, uprice, qty, uprice);')
w('')
w('        total := total + uprice * qty;')
w('      END LOOP;')
w('')
w('      UPDATE orders SET total_amount = total WHERE id = ord_id;')
w('    END LOOP;')
w('  END LOOP;')
w('END $$;')
w('')
w('-- end of seed')

const out = lines.join('\n')
const outPath = path.join(__dirname, '../src/seeds/seed.sql')
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, out, 'utf8')
console.log(`Written ${out.length} bytes to ${outPath}`)
console.log(`Lines: ${lines.length}`)
